# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_autoservices_resume_vakans_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prokat', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='show.Transport')),
            ],
            bases=('show.transport',),
        ),
    ]
